# Generated by Django 3.0.4 on 2020-04-27 04:26

import classes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('price', models.FloatField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, choices=[(classes.models.StateChoices['QUEUING'], 'Queuing'), (classes.models.StateChoices['DOING'], 'Doing'), (classes.models.StateChoices['DONE'], 'Done')], default=classes.models.StateChoices['QUEUING'], max_length=10, null=True)),
                ('total_price', models.FloatField(blank=True, max_length=10, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('customer_account_account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_owner', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('picture_restaurant', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('restaurant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_account_account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Owner')),
                ('type_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Order_List',
            fields=[
                ('list_no', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, max_length=50, null=True)),
                ('food_food_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Food')),
                ('order_order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Order')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant_restaurant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Restaurant'),
        ),
    ]
