# Generated by Django 3.0.4 on 2020-04-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200427_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='type_type_id',
            new_name='types',
        ),
    ]
