# Generated by Django 3.0.4 on 2020-04-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200425_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
