# Generated by Django 3.0.4 on 2020-04-28 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_auto_20200427_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='faculty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='picture',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='price',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='owner',
            name='picture_owner',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='open_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='picture_restaurant',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(max_length=50),
        ),
    ]
