# Generated by Django 3.0.4 on 2020-04-29 19:17

import classes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20200429_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Restaurant'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, choices=[(classes.models.StateChoices['SENDREQUEST'], 'SendRequest'), (classes.models.StateChoices['QUEUING'], 'Queuing'), (classes.models.StateChoices['DOING'], 'Doing'), (classes.models.StateChoices['DONE'], 'Done')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='price',
            field=models.IntegerField(max_length=50),
        ),
    ]
